name: CTT Design
favicon: null
layout_spectrum: 1
typography_spectrum: 0.66389
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cfd1de'
    - '#7f8b3f'
    - '#c8ba9f'
    - '#434135'
    - '#726346'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 0
purpose: []
